timeout: 5
serial: yes
wallpaper: no
interface_resolution: 1024x768

/ospab.os Live
    protocol: limine
    kernel_path: boot():/boot/KERNEL
    cmdline: mode=live
    module_path: boot():/boot/KERNEL
    module_cmdline: kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_cmdline: efi

/ospab.os Installer
    protocol: limine
    kernel_path: boot():/boot/KERNEL
    cmdline: mode=installer
    module_path: boot():/boot/KERNEL
    module_cmdline: kernel
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_cmdline: efi
