timeout: 5
serial: yes
wallpaper: no
interface_resolution: 1024x768

/ospab.os Live
    protocol: limine
    kernel_path: boot():/boot/KERNEL
    cmdline: mode=live

/ospab.os Installer
    protocol: limine
    kernel_path: boot():/boot/KERNEL
    cmdline: mode=installer
